### PR TITLE
Add parameters for bucket public policy

### PR DESCRIPTION
**Pull request by bman654**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Add "block public access" settings, defaulting to `false` to match previous behavior.

image

### CODE REVIEW

**Comment by michaelwittig** [comment]
Quick question before we add so many options to this module: What is your use case for controlling those settings at such a fine granular level? I usually turn all of them on except for public buckets. We could use the existing parameter `Access ` to check for public buckets.

**Comment by bman654** [comment]
yeah for me it is always all on or all off as well.  I thought about just tying it to `Access` but couldn't see how to do it without it being a breaking change.  Perhaps another "I really really mean private" allowed value for `Access`?

**Comment by michaelwittig** [comment]
I'm fine with releasing a version 2.0.0 :)

**Comment by bman654** [comment]
but I still think there are use cases for "private, but with exceptions", or "CloudFrontRead, with exceptions".  Perhaps a middle ground is to collapse the 4 options into a single "block all public access" boolean?

**Comment by michaelwittig** [comment]
@bman654 can you provide me an use case for "CloudFrontRead, with exceptions". I'm not sure if I can follow you. An example might help?

**Comment by bman654** [comment]
I don't know.  And maybe it's covered by your Custom option (which I don't understand how to use).  I've never had this use case, but perhaps there's a "I want to let CloudFront read it, and I also want to let specific objects in the bucket be publicly accessible".

It just strikes me that these block public access settings in AWS are intentionally separate security control that can override ACLs and if you model them using the same property you use to model ACLs (`Access`) then you eliminate the ability to control them separately.  Maybe that's entirely appropriate given the goals of this project -- someone wanting fine grained control can just write the cloudformation themselves after all.

**Comment by michaelwittig** [comment]
see #25

**Pull request closed without merging**
